################################################################################
# Custom Extension
################################################################################

ARG BAZEL_BASE_IMAGE=bazel-focal

# TODO: Configure the NAME somehow?
FROM arene-driving-docker-local-internal.artifactory-ha.tmc-stargate.com/bazel-zen:${BAZEL_BASE_IMAGE}

ENV BLESSING="May you be blessed by a tickle from his noodly apppendages..."

# Project specific customisation here
