[package]
name = "maliput_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
maliput = { version = "^0.1.2"}
clap = { version = "^4.5.4", features = ["derive"] }

[[bin]]
name = "road_geometry"
path = "src/road_geometry.rs"

[[bin]]
name = "traffic_lights"
path = "src/traffic_lights.rs"
